AllCops:
  Includes:
    - 'Rakefile'
    - 'Gemfile'
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
  RunRailsCops: true
  DisplayCopNames: true


# Ruby - Rubocopを使ってコーディングルールへの準拠チェックを自動化 - Qiita
# http://qiita.com/yaotti/items/4f69a145a22f9c8f8333

# 僕の使っている .rubocop.yml
# https://gist.github.com/onk/38bfbd78899d892e0e83


###### Style ######

# Whether `and` and `or` are banned only in conditionals (conditionals) or completely (always).
Style/AndOr:
  EnforcedStyle: conditionals

# Use only ascii symbols in comments.
Style/AsciiComments:
  Enabled: true

# Document classes and non-namespace modules.
Style/Documentation:
  Enabled: true

# Favor modifier if/unless usage when you have a single-line body.
Style/IfUnlessModifier:
  Enabled: true

# Favor modifier while/until usage when you have a single-line body.
Style/WhileUntilModifier:
  Enabled: false


###### Metrics ######

# Limit lines to 80 characters.
Metrics/LineLength:
  Enabled: false

# Avoid methods longer than 10 lines of code
Metrics/MethodLength:
  Enabled: false
