inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
#   - rubocop-rails
#   - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
