inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
#   - rubocop-rails
#   - rubocop-rake
#   - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
  - 'vendor/**/*'
  - 'spec/fixtures/**/*'
  - 'tmp/**/*'
  - '.git/**/*'
  - 'bin/*'
  TargetRubyVersion: 3.3

Metrics/MethodLength:
  Max: 20

Style/AsciiComments:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
