# ln -is $HOME/dotfiles/.warp $HOME/.warp
#
# Warp Launch Configuration
#
#
# Use this to start a certain configuration of windows, tabs, and panes.
# Open the launch configuration palette to access and open any launch configuration.
#
# This file defines your launch configuration.
# More on how to do so here:
# <https://docs.warp.dev/features/sessions/launch-configurations>
#
# All launch configurations are stored under ~/.warp/launch_configurations.
# Edit them anytime!
#
# You can also add commands that run on-start for your launch configurations like so:
# ---
# name: Example with Command
# windows:
#  - tabs:
#      - layout:
#          cwd: /Users/warp-user/project
#          commands:
#            - exec: code .
---
name: default
windows:
  - tabs:
      - title: dotfiles
        layout:
          cwd: /Users/shifumin/ghq/github.com/shifumin/dotfiles
        color: red
      - title: dotfiles2
        layout:
          cwd: /Users/shifumin/ghq/github.com/shifumin/dotfiles
        color: green
      - title: my-vault
        layout:
          cwd: "/Users/shifumin/Library/Mobile Documents/com~apple~CloudDocs/my-vault"
        color: yellow
      - title: my-vault2
        layout:
          cwd: "/Users/shifumin/Library/Mobile Documents/com~apple~CloudDocs/my-vault"
        color: blue
      - title: home5
        layout:
          cwd: /Users/shifumin
        color: magenta
      - title: home6
        layout:
          cwd: /Users/shifumin
        color: cyan
      - title: home7
        layout:
          cwd: /Users/shifumin
        color: white
